// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcsnqgppnyukconnffqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjc25xZ3Bwbnl1a2Nvbm5mZnFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MzU4NjIsImV4cCI6MjA2MDAxMTg2Mn0.lj8pPToGQqGn5eeqOTWZ5UL0rwZ8mx397CeEYyfxtII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);